### ISSUE TITLE
How to make it audiable?

### ISSUE THREAD

**Issue by willbasky** [tidalcycles/konnakol-gsoc#12]
Hi, I [tried](https://dev.to/aravindmohandas/visualising-konnakol-compositions-gsoc-22-update-2-16pc) to generate music and failed. 

```haskell
import Konnakol.Define
import System.Random ( mkStdGen)

d1 $ (tidalM Khanda rupaka Khanda (mkStdGen 112342))
```
Evaluating of these lines brought me nothing. Usual tidal code is audible at the same time. 

What should I do?

**Comment by aravind-mohandas** [comment]
Hi, have you loaded the [samples](https://github.com/tidalcycles/konnakol-gsoc/tree/main/audiofiles) in superDirt? That should be the reason there is no audio.

**Comment by willbasky** [comment]
Now, it works, thanks. 
Very cool thing you did.

One audio sample is missed:
```
no synth or sample named 'thak' could be found.
module 'sound': instrument not found: thak
```

**Comment by aravind-mohandas** [comment]
Thanks! I just noticed the missing audio sample, will be fixing that soon.
